Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -72,6 +72,15 @@ jobs:
         mkdir -p ${{ env.WORKDIR }}
         mkdir -p ${{ env.OUTDIR }}
 
+    - name: 🐞 Debug compiler test
+      run: |
+        echo "CC=$CC"
+        echo "SYSROOT=$SYSROOT"
+        echo "Trying to compile simple test..."
+        echo 'int main() { return 0; }' > test.c
+        $CC test.c -o test -fPIE -pie -I${SYSROOT}/usr/include -L${SYSROOT}/usr/lib || (echo "FAILED" && exit 1)
+        file test
+
     - name: 🧪 Configure PHP build (no SSL, no cURL)
       working-directory: ${{ env.WORKDIR }}
       run: |
